config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'posts#index'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  resources :users, only: %i[show] do
    get 'professional', on: :collection
    get 'myprofile', on: :member
    get 'selected_posts', on: :member
  end

  resources :posts do
    resources :comments
    get 'myposts', on: :collection
    post 'select_user', on: :member
    get 'application_users', on: :member
  end
  resources :bookmarks, only: %i[index create destroy]
  resources :applications, only: %i[index show create destroy]
  resources :categories
  resources :conversations, only: %i[index create] do
    resources :messages, only: %i[index create]
  end
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  belongs_to :parent,  class_name: 'Comment', optional: true
  has_many   :replies, class_name: 'Comment', foreign_key: :parent_id, dependent: :destroy

  validates :content, presence: true, length: { in: 1..255 }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @comment = current_user.comments.build(comment_params)
    respond_to do |format|
      if @comment.save
        format.js { render :index }
      else
        format.js { render :index }
      end
    end
  end

  def destroy
    @comment = current_user.comments.find(params[:id])
    @comment.destroy
    respond_to do |format|
      flash.now[:notice] = 'comment deleted'
      format.js { render :index }
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :post_id, :user_id, :parent_id)
  end
end

app/views/comments/_error.html.erb
<% if comment.errors.any? %>
<div class="error_message alert alert-warning">
  <ul>
    <% comment.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/comments/_form.html.erb
<%= form_with(model:[post,comment], url: post_comments_path(@post) ) do |form| %>
<% if comment.errors.any? %>
<div id="error_explanation">
    <ul>
      <% comment.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
</div>
<% end %>
<div class="row">
  <div class="form-group col-md-6">
    <p><label>New Thread</label></p>
    <%= form.text_area :content, class: "input-mysize" %>
  </div>
</div>

<%= form.hidden_field :post_id, value: post.id %>

<div class="actions">
  <%= form.submit %>
</div>
<% end %>

app/views/comments/_index.html.erb
<div id="comments_area">
  <% comments.each do |comment| %>
  <% unless comment.id.nil? %>
  <div class="comment">
    <p>
      <%= comment.content %><br>
      <%=comment.user.name%>
      date : <%= comment.created_at.strftime('%Y/%m/%d %H:%M:%S') %>
      <% if comment.user == current_user %>
      <%= link_to "delete", post_comment_path(comment.post_id, comment.id), method: :delete, remote: true, data: { confirm: "really delete?"} %>
      <% end %>
    </p>
  </div>
  <% end %>
  <% end %>
</div>

app/views/comments/destroy.js.erb
$('#comment_<%= @comment.id %>').remove();

app/views/comments/index.js.erb
$("#comments_area").html("<%= j(render 'index', { comments: @comment.post.comments.order(:created_at), post:@comment.post}) %>")
$("#comment-error").html("<%= j(render 'error', { comment: @comment }) %>")
$("textarea").val('')