config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'posts#index'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  resources :users, only: %i[show] do
    get 'professional', on: :collection
    get 'myprofile', on: :member
    get 'selected_posts', on: :member
  end

  resources :posts do
    resources :comments
    get 'myposts', on: :collection
    post 'select_user', on: :member
    get 'application_users', on: :member
  end
  resources :bookmarks, only: %i[index create destroy]
  resources :applications, only: %i[index show create destroy]
  resources :categories
  resources :conversations, only: %i[index create] do
    resources :messages, only: %i[index create]
  end
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :category_users, dependent: :destroy
  has_many :users, through: :category_users, source: :user
  has_many :category_posts, dependent: :destroy
  has_many :posts, through: :category_posts, source: :post
  validates :name, uniqueness: true
  validates :name, presence: true, length: { in: 1..50 }

  scope :select_category, ->(category) { where('categories.name = ?', category) }
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show edit update destroy]
  before_action :authenticate_user!

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def edit; end

  def show; end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to categories_path, notice: 'Successfully create Category'
    else
      flash[:danger] = 'Failed to save'
      render :new
    end
  end

  def update
    destroy_all_posts if params[:category][:post_ids].blank?
    destroy_all_users if params[:category][:user_ids].blank?
    if @category.update(category_params)
      redirect_to @category, notice: 'Successfully update Category'
    else
      flash[:danger] = 'Failed to update'
      render :edit
    end
  end

  def destroy
    @category.destroy!
    redirect_to categories_url, notice: 'Delete category'
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name, post_ids: [], user_ids: [])
  end

  def destroy_all_posts
    @category.posts.destroy_all
  end

  def destroy_all_users
    @category.users.destroy_all
  end
end

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>

  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "エラー") %> タスクの保存に失敗しました:</h2>
      <ul>
        <% category.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="form-group col-md-6">
      <p><label>category名</label></p>
      <input type="text" class="form-control input-form" name="category[name]" value="<%=@category.name%>">
    </div>
  </div>

    <div class="row">
    <div class="form-group col-md-6">
    <p>ユーザ一覧</p>
      <% User.all.each do |user| %>
        <%= form.check_box :user_ids, { multiple: true, checked: @category.user_ids.include?(user.id),disabled: user[:disabled], include_hidden: false }, user[:id] %>
        <label class='badge badge-secondary'><%= user.name %></label>
      <% end %>
    </div>
  </div>

    <div class="row">
    <div class="form-group col-md-6">
    <p>投稿一覧</p>
      <% Post.all.each do |post| %>
        <%= form.check_box :post_ids, { multiple: true, checked: @category.post_ids.include?(post.id),disabled: post[:disabled], include_hidden: false }, post[:id] %>
        <label class='badge badge-secondary'><%= post.title %></label>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="form-group col-md-6">
      <button type="submit" class="btn btn-primary" name="commit">登録</button>
    </div>
  </div>

<% end %>

app/views/categories/edit.html.erb
<h4>Edit Category</h4>

<%= render 'form' ,category: @category%>

<div class="row">
  <div class="form-group col-md-6">
    <p><%= link_to 'back', categories_path %></p>
  </div>
</div>

app/views/categories/index.html.erb
<div class="row">
  <h4> Category Index </h4>
</div>

<div class="table-responsive">
  <table class="table">
    <thead class="thead-light">
      <tr>
        <th>Title</th>
        <th>Users</th>
        <th>categorys</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @categories.each do |category| %>
      <tr>
        <td class="category_row"><%= category.name %></td>
        <td><% category.users.each do |category_user| %>
        <%= category_user.name %>
        <% end %>
        </td>
        <td><% category.posts.each do |category_post| %>
        <%= category_post.title %>
        <% end %>
        </td>
        <td><%= link_to 'detail', category %></td>
        <td><%= link_to 'edit', edit_category_path(category) %></td>
        <td><%= link_to 'destroy', category, method: :delete, data: { confirm: 'Really Delete Category?' } %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/categories/new.html.erb
<h4>Register Category</h4>

<%= render 'form' ,category: @category%>

<div class="row">
  <div class="form-group col-md-6">
    <p><%= link_to 'back', categories_path %></p>
  </div>
</div>

app/views/categories/show.html.erb
<h4>Category Detail</h4>

<div class="row">
  <div class="form-group col-md-6">
    <label>Category Name</label>
      <input type="text" readonly class="form-control show-form" value="<%=@category.name%>">
  </div>
</div>

<div class="row">
  <div class="form-group col-md-6">
    <label>Category Posts</label>
    <div>
      <% @category.posts.each do |post| %>
        <label class='badge badge-secondary'><%= post.title %></label>
      <% end %>
    </div>
  </div>
</div>

<div class="row">
  <div class="form-group col-md-6">
    <label>Category Users</label>
    <div>
      <% @category.users.each do |user| %>
        <label class='badge badge-secondary'><%= user.name %></label>
      <% end %>
    </div>
  </div>
</div>

<div class="row">
  <div class="form-group col-md-6">
    <%= link_to 'edit', edit_category_path(@category) %>
    <%= link_to 'back', categories_path %>
  </div>
</div>