config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'posts#index'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  resources :users, only: %i[show] do
    get 'professional', on: :collection
    get 'myprofile', on: :member
    get 'selected_posts', on: :member
  end

  resources :posts do
    resources :comments
    get 'myposts', on: :collection
    post 'select_user', on: :member
    get 'application_users', on: :member
  end
  resources :bookmarks, only: %i[index create destroy]
  resources :applications, only: %i[index show create destroy]
  resources :categories
  resources :conversations, only: %i[index create] do
    resources :messages, only: %i[index create]
  end
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/views/layouts/_applicants.html.erb
<!-- タイムライン表示画面 -->
<div class="col-md-8">
  <% @users.each {|user| %>
  <a href="/users/<%=user.id%>" class="post-link stretched-link">
    <div class="post mdl-shadow--2dp card clearfix">
      <div class="work-icon">
        <img src="<%=user.profile_image%>" alt="">
      </div>
      <div class="work-text">
        <div class="clearfix">
          <div class="post-text">
            <p class="post-title clearfix"><%= user.name %></p>
          </div>
          <div class="detail clearfix">
            <div class="detail">
              Detail : <%= user.content %>
            </div>
          </div>
          <div class="job-category">
            <p>Category :
              <% user.categories.each do |category| %>
              <span class="mdl-chip"><span class="mdl-chip__text">
                  <%= category.name %>
                </span>
              </span>
              <% end %>
            </p>
          </div>
        </div>
      </div>
    </div>
  </a>
  <% } %>
  <div><%= paginate @users, left: 1, right: 3 %></div>
</div>

app/views/layouts/_application_users.html.erb
   <tbody>
     <% users.each do |user| %>
     <tr>
       <td class="user-row"><%= link_to "#{user.name}", user %></td>
       <td><%= user.applications.find_by(post_id: post.id).created_at.strftime("20%y/%m/%d") %></td>
       <td><%= link_to 'message', conversations_path(sender_id: current_user.id, recipient_id: user.id), method: :post %>
       </td>
       <% if post.selected_user_id.blank? %>
       <td><a href="/posts/<%=post.id%>/select_user?selected_user_id=<%=user.id %>" data-method=post>Assign</a></td>
       <% else %>
       <% if post.selected_user_id == user.id %>
       <td>Assigned</td>
       <% else %>
       <td></td>
       <% end %>
       <% end %>
     </tr>
     <% end %>
   </tbody>

app/views/layouts/_applications.html.erb
<tbody>
  <% @posts.each do | post | %>
  <tr>
    <td><%= link_to "#{post.title}", post %></td>
    <td><%= post.recruiter.name %></td>
    <td><%= post.applications.count%></td>
    <td><%= post.deadline.strftime("20%y-%m-%d")%></td>
    <td class="status-<%=post.status%>"><%= post.status %></td>
  </tr>
  <% end %>
</tbody>

app/views/layouts/_bookmarks.html.erb
<tbody>
  <% @posts.each do | post | %>
  <tr>
    <td><%= link_to "#{post.title}", post %></td>
    <td><%= post.recruiter.name %></td>
    <td><%= post.applications.count%></td>
    <td><%= post.deadline.strftime("20%y-%m-%d")%></td>
    <td class="status-<%=post.status%>"><%= post.status %></td>
    <td><% my_bookmark = current_user.bookmarks.find_by(post_id: post.id) %>
      <a href="/bookmarks/<%=my_bookmark.id%>" data-method=delete>unbookmark</a></td>
  </tr>
  <% end %>
</tbody>

app/views/layouts/_footer.html.erb
<div class="footer">
  <div class="container">
    <ul id="menu-footer" class="common-footer__nav--list">
      <li id="menu-item-9" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-9">
        <p class="footer-item">会社</p>
      </li>
      <li id="menu-item-10" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-10">
        <p class="footer-item">プライバシーポリシー</p>
      </li>
      <li id="menu-item-11" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-11">
        <p class="footer-item">お問い合わせ</p>
      </li>
    </ul>


    <p class="copyright">Copyright © Junichi Sunaga All Rights Reserved.</p>
  </div>
  </footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbarExample1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="/posts">FindPro</a>
  </div>

  <div class="navbar-collapse navbar-right collapse" id="navbarExample1">
    <ul class="nav navbar-nav float-right">
      <% if user_signed_in? %>
      <li>
        <p class="navbar-text"><%= link_to "#{current_user.name}"+"[#{current_user.applicant_or_recruiter}]", myprofile_user_path(current_user) %></p>
      </li>
      <li>
        <% if current_user.admin %>
        <%= form_for(current_user, as: :user, url: user_registration_path, html: { name: "purpose",class: "", id: "freelancer-intro", method: :put }) do |f| %>
        <% purpose = current_user.applicant? ? 'recruiter' : 'applicant' %>
        <%= f.hidden_field :applicant_or_recruiter, value: purpose %>
        <p class="navbar-text"><a href="javascript:purpose.submit()">Switch to <%= purpose %></a></p>
        <% end %>
        <% end %>
      </li>
      <li>
        <p class="navbar-text"><%= link_to "All Posts", posts_path %></p>
      </li>
      <% if current_user.applicant? %>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Post Menu
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <p><%= link_to "Bookmark", bookmarks_path %></p>
          <p><%= link_to "Applied", applications_path %></p>
          <p><%= link_to "Selected", selected_posts_user_path(current_user) %></p>
        </div>
      </li>
      <% else %>
      <p class="navbar-text"><%= link_to "All Professionals", professional_users_path %></p>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Post Menu
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <%= link_to "New Posts", new_post_path, class:"dropdown-link" %>
          <%= link_to "My Recruiting Posts", myposts_posts_path, class:"dropdown-link" %>
        </div>
      </li>
      <% end %>
      <li>
        <p class="navbar-text"><%= link_to "Messages", conversations_path %></p>
      </li>
      <li>
        <p class="navbar-text"><%= link_to "Logout", destroy_user_session_path, method: :delete %></p>
      </li>
      <% else %>
      <li>
        <p class="navbar-text"><%= link_to "Sign-up", new_user_registration_path %></p>
      </li>
      <li>
        <p class="navbar-text"><%= link_to "Login", new_user_session_path %></p>
      </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/_myposts.html.erb
<tbody>
  <% @posts.each do | post | %>
  <tr>
    <td><%= link_to "#{post.title}", post %></td>
    <td><%= post.deadline.strftime("20%y/%m/%d") %></td>
    <td><%= post.bookmarks.count%></td>
    <% if post.applications.count == 0 %>
    <td><%= post.applications.count%></td>
    <% else %>
    <td><%= link_to "#{post.applications.count}", application_users_post_path(post) %></td>
    <% end %>
    <td><%= post.status %></td>
    <td>
      <% if post.status == 'open' %>
      <%= link_to 'edit',edit_post_path(post)%>
      <% end %>
    </td>
    <td><%= link_to 'delete',post_path(post),method: :delete, data: { confirm: "really delete?"}%></td>
  </tr>
  <% end %>
</tbody>

app/views/layouts/_notice.html.erb
<div class="notice-area">
<% flash.each do |key, value| %>
<%= content_tag(:div, value, class: "#{key}") %>
<% end %>
</div>

app/views/layouts/_posts.html.erb
<div class="col-md-8">
  <% @posts.each {|post| %>
  <a href="/posts/<%=post.id%>" class="post-link stretched-link">
    <div class="post mdl-shadow--2dp card clearfix">
      <div class="status open-term status-close clearfix">
        <div>
          <span class="mdl-chip-<%= post.status %>">
            <%= post.status %>
          </span>
        </div>
      </div>
      <div class="work-icon">
        <img src="<%=post.post_image%>" alt="">
      </div>
      <div class="work-text">
        <div class="clearfix">
          <div class="post-text">
            <p class="post-title clearfix post_title"><%= post.title %></p>
          </div>
          <div class="detail clearfix">
            <div class="deadline">
              Deadline : <%= post.deadline.strftime("20%y/%m/%d") %>
            </div>
          </div>
          <div class="job-category">
            <p>Category :
              <% post.categories.each do |category| %>
              <span class="mdl-chip"><span class="mdl-chip__text">
                  <%= category.name %>
                </span>
              </span>
              <% end %>
            </p>
          </div>
        </div>
      </div>
    </div>
  </a>
  <% } %>
  <div><%= paginate @posts, left: 1, right: 3 %></div>
</div>

app/views/layouts/_professional.html.erb
<!-- タイムライン表示画面 -->
<div class="col-md-8">
  <% @users.each {|user| %>
  <a href="/users/<%=user.id%>" class="post-link stretched-link">
    <div class="post mdl-shadow--2dp card clearfix">
      <div class="work-icon">
        <img src="<%=user.profile_image%>" alt="">
      </div>
      <div class="work-text">
        <div class="clearfix">
          <div class="post-text">
            <p class="post-title clearfix user_name"><%= user.name %></p>
          </div>
          <div class="detail clearfix">
            <div class="deadline">
              Register Date : <%= user.created_at.strftime("20%y/%m/%d") %>
            </div>
          </div>
          <div class="job-category">
            <p>Category :
              <% user.categories.each do |category| %>
              <span class="mdl-chip"><span class="mdl-chip__text">
                  <%= category.name %>
                </span>
              </span>
              <% end %>
            </p>
          </div>
        </div>
      </div>
    </div>
  </a>
  <% } %>
  <div><%= paginate @users, left: 1, right: 3 %></div>
</div>

app/views/layouts/_selected_posts.html.erb
<tbody>
  <% @posts.each do | post | %>
  <tr>
    <td><%= link_to "#{post.title}", post %></td>
    <td><%= post.recruiter.name %></td>
    <td><%= post.selected_user.name %></td>
    <td><%= post.status %></td>
  </tr>
  <% end %>
</tbody>

app/views/layouts/_sidebar_applicants.html.erb
<div class="user-search-left col-md-2 align-center clearfix">
  <h4>サイドメニュー</h4>
  <div class="sidemenu">
    <%= form_with url:'/users/applicants_index', method: :get, local: true do |f| %>
    <%= f.hidden_field :search, value: 'true' %>
    <div class="row clearfix">
      <div class="form-group search_form clearfix">
        <input type="text" class="form-control keyword-form clearfix" name="name" value="" placeholder="Keyword">
      </div>
      <div class="form-group search_form clearfix">
        <select class="form-control keyword-form clearfix" name="category">
          <option value="" style="display: none;">Label</option>
          <option value=""></option>
          <% @categories.each do |category| %>
          <option value=<%=category.name%>><%=category.name%></option>
          <% end %>
        </select>
      </div>
      <button type="submit" class="btn btn-primary search-btn" name="commit">検索</button>
    </div>
    <% end %>
  </div>
</div>

app/views/layouts/_sidebar_posts.html.erb
<div class="user-search-left col-md-2 align-center clearfix">
  <div class="sidemenu">
    <%= form_with url:'/posts', method: :get, local: true do |f| %>
    <%= f.hidden_field :search, value: 'true' %>
    <div class="row clearfix">
      <div class="form-group search_form clearfix">
        <%= search_form_for @q do |f| %>
        <%= f.search_field :title_or_detail_cont, class: 'form-control keyword-form clearfix', placeholder: 'keyword' %>
      </div>
      <div class="form-group search_form clearfix">
        <select class="form-control keyword-form clearfix" name="category">
          <option value="" style="display: none;">Category</option>
          <option value=""></option>
          <% @categories.each do |category| %>
          <% if  @category.present? && @category.name == category.name %>
          <option value="<%= category.name%>" selected><%= category.name %></option>
          <% else %>
          <option value="<%= category.name%>" ><%= category.name %></option>
          <% end %>
          <% end %>
        </select>
      </div>
      <button type="submit" class="btn btn-primary search-btn" name="commit">Search</button>
    </div>
    <% end %>
    <% end %>
  </div>
</div>

app/views/layouts/_sidebar_professional.html.erb
<div class="user-search-left col-md-2 align-center clearfix">
  <div class="sidemenu">
    <%= form_with url:'/users/professional', method: :get, local: true do |f| %>
    <%= f.hidden_field :search, value: 'true' %>
    <div class="row clearfix">
      <div class="form-group search_form clearfix">
        <%= search_form_for(@q,url: professional_users_path,method: :get) do |f| %>
        <%= f.search_field :name_or_content_cont, class: 'form-control keyword-form clearfix', placeholder: 'keyword' %>
      </div>
      <div class="form-group search_form clearfix">
        <select class="form-control keyword-form clearfix" name="category">
          <option value="" style="display: none;">Category</option>
          <option value=""></option>
          <% @categories.each do |category| %>
          <% if  @category.present? && @category.name == category.name %>
          <option value="<%=category.name%>" selected><%= category.name %></option>
          <% else %>
          <option value="<%=category.name%>"><%= category.name %></option>
          <% end %>
          <% end %>
        </select>
      </div>
      <button type="submit" class="btn btn-primary search-btn" name="commit">Search</button>
    </div>
    <% end %>
    <% end %>
  </div>
</div>